### ISSUE TITLE
Negative numbers may not be handled properly

### ISSUE THREAD

**Issue by jvsalo** [jsuvanto/fraction#3]
The code doesn't appear to make effort to canonicalize representation of negative numbers.

This can break operator==(). Unfortunately I couldn't pinpoint a broken case because the simplify() function always appears to fix the negative value to either both denominators or both numerators (which ones, it varies depending on the actual numbers). But this appears to work by accident.

**Comment by jsuvanto** [comment]
This will be fixed in the next commit. Sign will be stored in the numerator only. This will make usage of the class and especially the simplify() method more consistent.
